config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect("/bands")
  resources :users, only: [:show, :new, :create]
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only:[:create, :show, :edit, :destroy, :update] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only:[:create, :show, :edit, :destroy, :update]
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :tracks, dependent: :destroy
  belongs_to :band

  validates :band_id, :name, :year, presence: true
  validates :year, numerically: { minimum: 1900, maximum: 9000 }
  validates :name, uniqueness: { scope: :band_id }
  validates :live, inclusion: { in: [true, false] }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :albums, dependent: :destroy

  validates :name, presence: true, uniqueness: true


end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
  has_one :band, through: :album, source: :band

  validates :album_id, :name, :lyric, :ord, presence: true
  validates :ord, uniqueness: { scope: :album_id}
  validates :bonus, inclusion: { in: [true, false]}


end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user & user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # before_action :require_user!

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to band_url(@album)
    else
      @band = @album.band
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  private

  def album_params
    params.require(:album).permit(:band_id, :name, :year, :live)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def require_user!
    redirect_to new_session_url if current_user.nil?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  # before_action :require_user!

  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destory
    redirect_to bands_url
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password])

    if user.nil?
      flash[:errors] = ["Invalid credentials."]
      render :new
    else
      login_user!(user)
      redirect_to root_url
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end



end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_user!

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new(album_id: params[:album_id])
    render :new
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      @album = @track.album
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to album_url(@track.album_id)
  end

  def update
    @track = Track.find(params[:id])

    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  private

  def track_params
    params.require(:track).permit(:album_id, :name, :bonus, :ord)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # UserMailer.welcome_email(@user).deliver_now!
      login_user!(@user)
      redirect_to new_session_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<% action_url = album.persisted? ? album_url(album) :  %>
<% http_method = album.persisted? ? "PATCH" : "POST" %>
<% button_text = album.persisted? ? "Update Album!" : "Create Album!" %>

<form action="action_url" method="POST">
  <input type="hidden" name="_method" value="http_method">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label>Name
    <input type="text" name="album[name]" value="<%= album.name %>">
    </label>
  </p>

  <p>
    <label>Band
      <select name="album[band_id]">
        <% Band.all.each do |band| %>
          <option
            <%= "selected" if album.band_id == band.id %>
            value="<%= band.id %>">
            <%= band.name %>
          </option>
        <% end %>
      </select>
    </label>
  </p>

  <p>
    <input
      type="radio"
      name="album[live]"
      value="t"
      id="album_live_t"
      <%= "checked" if album.live %>>
    <label for="album_live_t">Live</label>
    <input
      type="radio"
      name="album[live]"
      value="s"
      id="album_live_s"
      <%= "checked" if !album.live %>>
    <label for="album_live_s">Studio</label>
  </p>

  <p>
    <label>Year
      <input type="number" name="album[year]" value="<%= album.year %>">
    </label>
  </p>

  <input type="submit" value="<%= button_text %>">

</form>

app/views/albums/new.html.erb
<h1>New <%= @band.name %> album</h1>

<%= render "form", album: @album %>

app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% http_method = band.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <p>
    <label>Name
    <input type="text" name="band[name]" value="<%= band.name %>">
    </label>
  </p>

  <input type="submit">

</form>

app/views/bands/index.html.erb
<h1>All bands</h1>

  <ul>
    <% @bands.each do |band| %>
      <li><a href="<%= band_url(band) %>"><%= band.name %></a></li>
    <% end %>
  </ul>

<%= link_to "New band", new_band_url %>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render "form", band: @band %>

app/views/bands/show.html.erb
<h1><%= band_url(@band) %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <% if logged_in? %>
    <nav>
      <p>logged in as: <%= current_user.email %></p>
      <%= button_to "Sign out", session_url, method: :delete %>
    </nav>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tracks/_form.html.erb
<% action_url track.persisted? ? track_url(track) : tracks_url %>
<% http_method track.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="post">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label>Name
      <input type="text" name="track[name]" value="<%= track.name %>">
    </label>
  </p>

  <p>
    <select name="track[album_id]">
      <% Album.all.each do |album| %>
        <option
          <%= "selected" if track.album_id == album.id %>
          value="<%= track.id %>">
          <%= album.name %>
        </option>
      <% end %>
    </select>
  </p>

  <p>
    <input
      type="radio"
      name="track[bonus]"
      value="t"
      id="track_bonus_t">
    <%= "checked" if track.bonus %>
    <label for="track_bonus_t">Bonus</label>
    <br>
    <input
      type="radio"
      name="track[bonus]"
      value="f"
      id="track_bonus_f">
    <%= "checked" if !track.bonus %>
    <label for="track_bonus_f"></label>
  </p>

  <p>
    <label>Ord
      <input type="number" name="album[ord]" value="<%= album.ord %>">
    </label>
  </p>

  <p>
    <label for="track_lyric">Lyrics</label><br>
    <textarea
      id="track_lyric"
      rows="8" cols="80"
      name="track[lyric]">
      <%= track.lyric %>
    </textarea>
  </p>

  <input type="submit">

</form>

app/views/users/new.html.erb
<h1>New user</h1>

or <%= link_to "Sign in now!", new_session_url %>

<form action="<%= user_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label>Email</label>
    <input type="text" name="user[email]">
  </p>

  <p>
    <label>Password</label>
    <input type="password" name="user[password]">
  </p>

  <input type="submit" value="create user">

</form>

app/views/users/show.html.erb
<h1>User Profile</h1>

<p>
  Email: <%= current_user.email %>
</p>